# Generated by Django 5.0.14 on 2026-01-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_visit_geo_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visit',
            name='analytics_v_started_eb50d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='analytics_v_visitor_1fdfcb_idx',
        ),
        migrations.RemoveField(
            model_name='dailyrollup',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='dailyrollup',
            name='avg_duration_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrollup',
            name='avg_scroll',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrollup',
            name='conversions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyrollup',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailyrollup',
            name='pageviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyrollup',
            name='path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dailyrollup',
            name='sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyrollup',
            name='unique_visitors',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='action',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='label',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='event',
            name='path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='scroll_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='performance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='visit',
            name='browser',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='visit',
            name='city',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='visit',
            name='country',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='visit',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='visit',
            name='landing_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='visit',
            name='language',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='visit',
            name='os',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='visit',
            name='session_id',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='utm_campaign',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='visit',
            name='utm_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='visit',
            name='utm_medium',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='visit',
            name='utm_source',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='visit',
            name='utm_term',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visitor_id',
            field=models.UUIDField(),
        ),
    ]
