# Generated by Django 5.0.14 on 2026-01-11 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_visit_analytics_v_started_eb50d2_idx_and_more'),
        ('analytics', '0003_visit_geo_sources'),
    ]

    operations = [
    ]
